# Generated by Django 3.1.12 on 2022-06-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20220616_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
