# Generated by Django 3.1.12 on 2022-05-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_owner_speciality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='speciality',
        ),
        migrations.AddField(
            model_name='doctors',
            name='speciality',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
