# Generated by Django 3.1.12 on 2022-06-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20220616_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='owner',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
