# Generated by Django 3.1.12 on 2022-07-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_userinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='isHospital',
            field=models.BooleanField(default=False),
        ),
    ]
