# Generated by Django 3.1.12 on 2022-06-02 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_hospital_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='hospital',
            new_name='user',
        ),
    ]
