# Generated by Django 3.1.12 on 2022-06-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
