# Generated by Django 3.1.12 on 2022-06-09 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_auto_20220609_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='feature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.feature'),
        ),
    ]
