# Generated by Django 3.1.12 on 2022-07-07 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20220707_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.hospitalinformation'),
        ),
    ]
