# Generated by Django 3.1.12 on 2022-06-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_booking_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='email',
        ),
        migrations.AddField(
            model_name='hospital',
            name='display_photo',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
