# Generated by Django 3.1.12 on 2022-07-07 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_hospitalimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.hospitalinformation'),
        ),
    ]
